# Generated by Django 5.0 on 2025-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="password_reset_token",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="password_reset_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
